# Generated by Django 5.1.4 on 2025-01-02 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_customer_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('ADVENCED..', 'Advenced')], max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('delivery_crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_crew', to=settings.AUTH_USER_MODEL)),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderitem')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shippingaddress')),
            ],
        ),
    ]
