# Generated by Django 5.1.4 on 2025-01-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
